ktor:
  application:
    modules:
      - com.github.radlance.ktormessagingapi.ApplicationKt.module
  deployment:
    port: 8080
postgres:
  url: "jdbc:postgresql://localhost/default"
  user: username
  password: password
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
