ktor:
  application:
    modules:
      - com.github.radlance.ktormessagingapi.ApplicationKt.module
  deployment:
    port: 8080
database:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/messaging_api
  user: postgres
  password: 1
jwt:
  secret: 2073c058c51b800e476b7b44988fd22f
  expiration: 43200000
  total-expiration: 1209600000
  issuer: http://localhost:8080
  domain: http://localhost:8080
  audience: users