--liquibase formatted sql

--changeset dmitry:1

CREATE TABLE IF NOT EXISTS chat
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type       VARCHAR(6) NOT NULL,
    title      VARCHAR(64),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);