--liquibase formatted sql

--changeset dmitry:1

CREATE TABLE IF NOT EXISTS message
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id    INTEGER REFERENCES chat (id) ON DELETE CASCADE,
    sender_id  INTEGER REFERENCES users (id) ON DELETE CASCADE,
    text       TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    is_deleted BOOLEAN   DEFAULT FALSE
);