--liquibase formatted sql

--changeset dmitry:1

CREATE TABLE IF NOT EXISTS message_read_status
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id INT NOT NULL REFERENCES message (id) ON DELETE CASCADE,
    user_id    INT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    read_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (message_id, user_id)
);